version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.6.6
  security:
    docker:
      - image: aquasec/trivy:latest

jobs:
  terraform-validate:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: cd infra && terraform init -backend=false
      - run:
          name: Terraform Validate
          command: cd infra && terraform validate || echo "Terraform validation failed, but continuing..."
      - run:
          name: Terraform Format Check
          command: cd infra && terraform fmt -check -recursive || echo "Format check failed, but continuing..."

  yaml-lint:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: |
            apk add --no-cache yamllint
      - run:
          name: Lint YAML Files
          command: |
            yamllint apps/ -f parsable || echo "YAML linting warnings found, but continuing..."
            yamllint infra/ -f parsable || echo "YAML linting warnings found, but continuing..."
            yamllint .circleci/ -f parsable || echo "YAML linting warnings found, but continuing..."

  security-scan:
    executor: security
    steps:
      - checkout
      - run:
          name: Scan for Vulnerabilities
          command: |
            trivy fs --security-checks vuln,config,secret .
            trivy config .
      - run:
          name: Scan Container Images
          command: |
            trivy image mailhog/mailhog:v1.0.1
            trivy image mailhog/mailhog:latest

workflows:
  version: 2
  validate:
    jobs:
      - terraform-validate
      - yaml-lint
      - security-scan:
          filters:
            branches:
              only: master
          # Only run if any required job fails
          # CircleCI does not support 'on_fail' directly, so this job should be triggered manually or by a failed job using 'when: on_fail' if using CircleCI 2.1+ advanced features.
