version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.6.6
  security:
    docker:
      - image: aquasec/trivy:latest
  mailer:
    docker:
      - image: alpine:latest

jobs:
  terraform-validate:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: cd infra && terraform init -backend=false
      - run:
          name: Terraform Validate
          command: cd infra && terraform validate || echo "Terraform validation failed, but continuing..."
      - run:
          name: Terraform Format Check
          command: cd infra && terraform fmt -check -recursive || echo "Format check failed, but continuing..."

  yaml-lint:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: |
            apk add --no-cache yamllint
      - run:
          name: Lint YAML Files
          command: |
            yamllint apps/ -f parsable || echo "YAML linting warnings found, but continuing..."
            yamllint infra/ -f parsable || echo "YAML linting warnings found, but continuing..."
            yamllint .circleci/ -f parsable || echo "YAML linting warnings found, but continuing..."

  security-scan:
    executor: security
    steps:
      - checkout
      - run:
          name: Scan for Vulnerabilities
          command: |
            trivy fs --security-checks vuln,config,secret .
            trivy config .
      - run:
          name: Scan Container Images
          command: |
            trivy image mailhog/mailhog:v1.0.1
            trivy image mailhog/mailhog:latest

  notify-on-failure:
    executor: mailer
    steps:
      - run:
          name: Install mailx
          command: apk add --no-cache mailx msmtp
      - run:
          name: Send Failure Notification
          command: |
            echo "CircleCI pipeline failed for job: $FAILED_JOB on branch: $CIRCLE_BRANCH. Check the CircleCI dashboard for details." | \
            mailx -v -s "[ALERT] CircleCI Pipeline Failed" -S smtp-use-starttls -S ssl-verify=ignore \
            -S smtp=smtp://$SMTP_SERVER:$SMTP_PORT \
            -S smtp-auth=login -S smtp-auth-user=$SMTP_USER -S smtp-auth-password=$SMTP_PASS \
            -S from="$SMTP_USER" tandapnoelbansikah@gmail.com

workflows:
  version: 2
  validate:
    jobs:
      - terraform-validate
      - yaml-lint
      - security-scan:
          filters:
            branches:
              only: master
      - notify-on-failure:
          requires:
            - terraform-validate
            - yaml-lint
            - security-scan
          filters:
            branches:
              only: master
          # Only run if any required job fails
          # CircleCI does not support 'on_fail' directly, so this job should be triggered manually or by a failed job using 'when: on_fail' if using CircleCI 2.1+ advanced features.
