apiVersion: v1
kind: Service
metadata:
  name: mailhog-demo
spec:
  selector:
    app: mailhog-demo
  ports:
  - name: http
    protocol: TCP
    port: 8025
    targetPort: 8025
  - name: smtp
    protocol: TCP
    port: 1025
    targetPort: 1025
  type: ClusterIP

