---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog-demo
spec:
  project: default
  source:
    repoURL: https://github.com/bansikah22/gitops-demo
    targetRevision: HEAD
    path: apps/overlays/dev   # dev overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
